[package]
name = "index_tree"
version = "0.1.1"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = "0.5.1"

[profile.release]
debug = true

[[bench]]
name = "benchmark"
harness = false
bench = false